### ISSUE TITLE
'QgsVectorLayerEditBuffer' object has no attribute 'allAddedOrEditedFeatures'

### ISSUE THREAD

**Issue by SebastienPeillet** [hytechimaging/sammo-boat#119]
https://github.com/hytechimaging/sammo-boat/blob/main/src/core/session.py#L160

'QgsVectorLayerEditBuffer' object has no attribute 'allAddedOrEditedFeatures'

This method has been added in QGIS 3.20 so it's not available in the LTR yet

**Comment by pblottiere** [comment]
Arrghh...
