### ISSUE TITLE
KeyError `speed` when no valid frame yet

### ISSUE THREAD

**Issue by pblottiere** [hytechimaging/sammo-boat#151]
![key_error_speed](https://user-images.githubusercontent.com/9266424/161933244-47fa8c4a-0600-4769-804d-eeeae473c7dc.png)

**Comment by SebastienPeillet** [comment]
It's because now the key is ["gprc"]["speed"], I fixed it on #149

**Comment by pblottiere** [comment]
I just pull the last commit and the error is gone :+1:
